# Generated by Django 4.2.20 on 2025-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade_Calc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_file", models.FileField(default="models.py", upload_to="")),
                ("input_data", models.CharField(default="", max_length=300)),
                ("output_filename", models.CharField(default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
