# Generated by Django 4.2.20 on 2025-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade_calc", old_name="input_data", new_name="input_data1",
        ),
        migrations.RenameField(
            model_name="grade_calc", old_name="input_file", new_name="input_file1",
        ),
        migrations.AddField(
            model_name="grade_calc",
            name="input_data2",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="grade_calc",
            name="input_file2",
            field=models.FileField(default="models.py", upload_to=""),
        ),
    ]
