# Generated by Django 4.2.20 on 2025-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_input_data1_grade_calc_input_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade_calc",
            name="input_data2",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="grade_calc",
            name="input_file2",
            field=models.FileField(default="models.py", upload_to=""),
        ),
    ]
